version: "3.7"

services:
    flask:
        build: ./flask
        container_name: flask
        network_mode: "service:nginx"
        depends_on: 
            - nginx
    nginx:
        image: nginx:1.19.4
        container_name: nginx
        
        ports: 
            - "8080:80"

        volumes:
            - ./data/nginx:/etc/nginx/conf.d